version: "3.2"
services:
  db:
    image: mongo:5.0
    container_name: db
    restart: always
    ports: 
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: desafio_mutual
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    container_name: api
    depends_on:
      - db
    environment:
      NODE_ENV: development
    image: node:latest
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - ${APP_PORT}:3000
    restart: always
    volumes:
      - .:/home/app/desafio-mutual
      - /home/app/desafio-mutual/node_modules
    working_dir: /home/app/desafio-mutual